### ISSUE TITLE
rule set for fragment depiction

### ISSUE THREAD

**Issue by dgcovell** [CDK-R/depict#12]
Zach, 
Exploring depict for highlighting fragments/substructures is small molecules. Can you tell me why all of the substructures
do not get highlighted in the parent molecule. That is, if I highlight only one fragment at a time, I should get an image with 
that fragment displayed. I am sure that the rules used for assignment are not fixed. However, you can suggest a way to 
highlight each fragment that would be helpful.

Regards,
David

parent
[1] "CC(n1c(C)ncc1c1ccnc(n1)Nc1ccc(cc1)S(=O)(=O)C)C CMGC:CDC2:6gu3:A:FB8 792"
fragments
[1] "N=1[N]c2ccccc2C1 frag121"
[1] "n1cccnc1-c2ccccc2 frag1662"
[1] "c1ccc(cc1)N2CCN(CC2)CCN3CCCC3 frag1988"
[1] "n1cccnc1-c2ccc(cc2)N3CCNCC3 frag1995"
[1] "N1CCN(CC1)CCN2CCCC2 frag1998"
[1] "N=1[N]c2ccc(cc2C1)NCC3CNCC3 frag2136"
[1] "n1ccc(cc1)C2=N[N]c3ccccc32 frag2139"

**Comment by zachcp** [comment]
Hi @dgcovell,

Can you post a full example so I can see what you are doing?

zach cp

**Comment by dgcovell** [comment]
Zach, Thanks. I am sure this answer is buried somewhere in the smiles representation. I am trying to highlight the substructure with the IUPAC name of 3-pyridin-4-yl-1H-indazole. The section below lists the steps for highlighting. The parent structure is in tmp_smi and the substructure is in tmp_frag. The rendered figure does not highlight this portion of the parent molecule. I have tried a few modifications in the smiles but with no luck. For the most part with other cases, the highlighting is fine. This and a few others are not being displayed. Tautomers will probably be the problem.
Regards,
David



```r
i_targ <- 1628
tmp_smi <- drugs_KLIFS_unique$smiles[i_targ]
# tmp_smi
# [1] "O=C(N1CCN(CC1)c1ccc(cc1)c1ncccn1)CN1CC[C@H](C1)C(=O)Nc1ccc2c(c1)c(n[nH]2)c1ccncc1"
tmp_label <- drugs_KLIFS_unique$generic_name[i_targ]
# [1] "CMGC:CDC2:6gu3:A:FB8"
pen <- parse_smiles(paste(tmp_smi, tmp_label,sep=" "))
atms <- pen$atoms()
bnds <- pen$bonds()
tmp_frag <- allfrags_KLIFS_unique[2139]
# [1] "n1ccc(cc1)C2=N[N]c3ccccc32"
cav <- parse.smiles(tmp_frag)
lactam <- match_smarts(tmp_frag, pen)
depiction() %>%
  highlight_atoms(atms, color$LIGHT_GRAY) %>%
  highlight_atoms(bnds, color$LIGHT_GRAY) %>%
  highlight_atoms(lactam, color$GREEN) %>%
  set_size(1400, 1400) %>%
  set_zoom(4) %>%
  outerglow() %>%
#             add_title() %>%
  depict(pen) %>%
  get_image() %>%
  grid::grid.raster()


```

**Comment by dgcovell** [comment]
do not know what is up with the cut and paste, but if you eliminate all but the text you have the depict calls

**Comment by schymane** [comment]
I find the CDK depict website super useful to debug these cases, without trying I'd guess indeed that it's the aromatic tautomers causing the issue... but this really helps explore the effect of tweaking the smarts/ substructure on the recognition:

https://www.simolecule.com/cdkdepict/depict.html



-------------------------------------------
PI: EnvChemInf @ LCSB
FNR ATTRACT Fellow
***@***.***
________________________________

**Comment by dgcovell** [comment]
schymane, thanks for you comment. i have tried a number of modifications for the posted example. none appear to work. if you are familiar with how to proceed for my example please comment.
regards,
david

**Comment by dgcovell** [comment]
Zach and others,

any update would be greatly appreciated. 

Thanks,
David

**Comment by zachcp** [comment]
addressed in https://github.com/CDK-R/cdkr/issues/137; closing.
