### ISSUE TITLE
Highlighting specific atoms

### ISSUE THREAD

**Issue by stanstrup** [CDK-R/depict#5]
Is there a way to highlight specific atoms for example by combining with `rcdk::get.stereocenters`?

**Comment by zachcp** [comment]
There is no fundamental reason why not and this could be an interesting addition to the docs. Do you have a molecule and an expected output that we can use as an example? If so I can help put together a working example.

**Comment by stanstrup** [comment]
Thanks for taking a look.
Ideally I would like to be able to do something like:

```r
  color <- J("java.awt.Color")
  mol  <- parse.smiles("C[C@H]([C@@H](C(=O)O)N)O")[[1]]
  
  mark <- get.stereocenters(mol)
  mark <- (mark & get.element.types(mol)=="Tetracoordinate") %>% which
    
  
  dep <- depiction() %>%
  highlight_atoms(get.atoms(mol)[mark], color$RED) %>% # cannot currently do this
  set_zoom(3)
    
  dep <- dep$withAtomColors()$withAtomNumbers()
    
  dep %>% 
  depict(mol) %>%
  get_image() %>%
  grid::grid.raster()
```

It should mark atom 2 and 3.

**Comment by zachcp** [comment]
Can you try this?

```R
library(depict)
library(magrittr)

#' match_stereo
#' 
#' return a hashset of Atoms that have the specified sterochemistry
#' 
match_stereo <- function(mol, stereo_type="Tetracoordinate") {
  
  hashset   <- J("java/util/HashSet")
  highlight <- new(hashset)
  
  stereos   <- J("org/openscience/cdk/stereo/Stereocenters")
  highlight <- new(hashset)
  centers   <- stereos$of(mol)
  
  # java is 0-indexed
  for (i in seq(0, mol$getAtomCount()-1, 1)) {
    idx_int <- as.integer(i)
    center  <- centers$isStereocenter(idx_int)
    
    if (center == TRUE) {
      center_type <- centers$elementType(idx_int)
      
      if (center_type$toString() == stereo_type) {
          atm <- mol$getAtom(idx_int)
          highlight$add(atm)
      }
    }
  }
  
  highlight
}



color  <- J("java.awt.Color")
mol    <- parse_smiles("C[C@H]([C@@H](C(=O)O)N)O")
stereo <- match_stereo(mol)


depiction() %>%
  highlight_atoms(stereo, color$RED) %>% 
  set_zoom(3) %>%
  depict(mol) %>%
  get_image() %>%
  grid::grid.raster()

```



![Screen Shot 2020-03-04 at 2 43 35 PM](https://user-images.githubusercontent.com/1260667/75916499-769d2600-5e26-11ea-8183-0d873b91d5a7.png)

**Comment by stanstrup** [comment]
Yes! Thanks works.
Would it be possible though to have the highlight using an outline like the penicillin example so that the marking is distinctly different from what you get with `withAtomColors`?
With your example combining the marking of stereocenters with `withAtomColors` could be confusing.

**Comment by zachcp** [comment]
```R
# use outerglow()

depiction() %>%
  highlight_atoms(stereo, color$RED) %>% 
  set_zoom(3) %>%
  outerglow() %>%
  depict(mol) %>%
  get_image() %>%
  grid::grid.raster()
```

![Screen Shot 2020-03-04 at 3 39 13 PM](https://user-images.githubusercontent.com/1260667/75920908-3cd01d80-5e2e-11ea-9204-7cb2ad3b3e07.png)

**Comment by stanstrup** [comment]
Yes! That is what I was after.

This would be a nice addition IMO.
Wouldn't a general function that takes the atom numbers to highlight be more generally useful?

```r

  highlist_atoms <- function(mol, idx) {
    
    hashset   <- J("java/util/HashSet")
    highlight <- new(hashset)
    
    # java is 0-indexed
    for (i in (idx-1)) {
      idx_int <- as.integer(i)
      atm <- mol$getAtom(idx_int)
      highlight$add(atm)
    }
     
    highlight
  }
  
  
  
  
  
  color <- J("java.awt.Color")
  mol  <- parse_smiles("C[C@H]([C@@H](C(=O)O)N)O")
  mol2  <- parse.smiles("C[C@H]([C@@H](C(=O)O)N)O")[[1]]
  
  mark <- get.stereocenters(mol2)
  mark <- (mark & get.element.types(mol2)=="Tetracoordinate") %>% which
    
  
  stereo <- highlist_atoms(mol, idx = mark)
  
  
  dep <- depiction() %>%
  highlight_atoms(stereo, color$RED) %>% 
  set_zoom(3)
    
  dep <- dep$withAtomColors()$withAtomNumbers()
    
  dep %>% 
  outerglow() %>%
  depict(mol) %>%
  get_image() %>%
  grid::grid.raster()
```

![image](https://user-images.githubusercontent.com/4532682/75922282-ffd24e00-5e62-11ea-9ca4-ecfc36083804.png)

**Comment by zachcp** [comment]
@stanstrup , for the purpose of this library I would like to follow the API of depict which means supplying the highlight codes with a hashset of atoms.  

If highlighting specific atom nubmer sis important I would write a select function that take a molecule and returns a hashset of atoms that match the number or nunbers. If you think thing that would be useful, can you write a new issue and request it as a feature?
