### ISSUE TITLE
multiple panels and java.awt.Color

### ISSUE THREAD

**Issue by dgcovell** [CDK-R/depict#9]
I do not consider this as an 'issue', but more of a novice user trying to gain a better understanding. I recently discovered the 'depict' package and have started using it for identifying fragments in structures. Since I have not found answers to three questions about implementation and am hoping this request will provide them.

1. I have not found how to create a multi-panel image (i.e.  par(mfrow=c(1,2)). The answer is most likely within the grid.raster parameters. Is there a syntax for doing this?
2. I would like to modify the command  "highlight_atoms(lactam, color$RED) %>%" , from the depict example, to allow a spectrum of colors. So far I have not been able to identify the color wheel, nor the
 syntax for doing so. str(color) gives me no information, Ideally color$ALL would be helpful.
3. Is it possible to overlay highlights with different colors and widths of the displayed bonds on the same parent structure?

Thanks in advance,
David

**Comment by zachcp** [comment]
David, 

1. Check out the current code I stubbed out an example [here](https://cdk-r.github.io/depict/articles/Basic-Use.html#multiple-smiles).
2. for this you would need to specify the color directly. These are actually Java colors. Any color you can generate in [Java](https://docs.oracle.com/javase/8/docs/api/java/awt/Color.html), you can use here but you will need to generate the color codes.
3. You should be able to specify bond widths and colors, yes. Although I am not sure the best way to modify specific bonds. Do you have an example image?


Sorry for the slow reply.

zach cp

**Comment by dgcovell** [comment]
Zach, Thanks for the reply. I found your example at the github site. Here's what I get:

> atmcontainers <-  purrr::map(
+   c("CCCC", "CCCCCC", "CCCC1CCC1CC2CCCC2"),
+   parse_smiles)
> many_containers <- atomcontainer_list_to_jarray(atmcontainers)
>
> depiction() %>%
+   set_zoom(10) %>%
+   depict(many_containers) %>%
+   get_image() %>%
+   grid::grid.raster()
Error in depict(., many_containers) : depict requires an AtomContainer

Don't seem to have the correct code for 
atomcontainer_list_to_jarray

which I took from above the section in the github example for mutiple smiles.

If you see this soon, having some control over font size/color would be great. have not found how this
can be done using setup parameters. Can you advise??

Regards,
David

**Comment by zachcp** [comment]
try to install the latest `depict` code.  Below should work fine

```r
# install.packages("devtools")
devtools::install_github("CDK-R/depict")

library(depict)

# load a few smiles as AtomContainers
atmcontainers <-  purrr::map(
  c("CCCC", "CCCCCC", "CCCC1CCC1CC2CCCC2"),
  parse_smiles)

# convert them into a java iterable  
many_containers <- atomcontainer_list_to_jarray(atmcontainers)


depiction() |>
  set_zoom(10) |>
  depict(many_containers)|>
  get_image() |>
  grid::grid.raster()

```
